// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBContent.proto

package io.nettyex.tinytransport.test;

public final class PBContent {
  private PBContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code tinytransport.Cmd}
   */
  public enum Cmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INVALID = 0;</code>
     */
    INVALID(0),
    /**
     * <code>GET_PERSONINFO = 1;</code>
     */
    GET_PERSONINFO(1),
    /**
     * <code>GET_PERSONINFO_RES = 2;</code>
     */
    GET_PERSONINFO_RES(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>INVALID = 0;</code>
     */
    public static final int INVALID_VALUE = 0;
    /**
     * <code>GET_PERSONINFO = 1;</code>
     */
    public static final int GET_PERSONINFO_VALUE = 1;
    /**
     * <code>GET_PERSONINFO_RES = 2;</code>
     */
    public static final int GET_PERSONINFO_RES_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cmd valueOf(int value) {
      return forNumber(value);
    }

    public static Cmd forNumber(int value) {
      switch (value) {
        case 0: return INVALID;
        case 1: return GET_PERSONINFO;
        case 2: return GET_PERSONINFO_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
            public Cmd findValueByNumber(int number) {
              return Cmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.nettyex.tinytransport.test.PBContent.getDescriptor().getEnumTypes().get(0);
    }

    private static final Cmd[] VALUES = values();

    public static Cmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Cmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tinytransport.Cmd)
  }

  public interface ProtoContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tinytransport.ProtoContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 cmd = 1;</code>
     */
    int getCmd();

    /**
     * <code>optional int32 errCode = 2;</code>
     */
    int getErrCode();

    /**
     * <code>optional string errMsg = 3;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string errMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <code>optional bytes data = 20;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code tinytransport.ProtoContent}
   */
  public  static final class ProtoContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tinytransport.ProtoContent)
      ProtoContentOrBuilder {
    // Use ProtoContent.newBuilder() to construct.
    private ProtoContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoContent() {
      cmd_ = 0;
      errCode_ = 0;
      errMsg_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cmd_ = input.readInt32();
              break;
            }
            case 16: {

              errCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errMsg_ = s;
              break;
            }
            case 162: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_ProtoContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_ProtoContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nettyex.tinytransport.test.PBContent.ProtoContent.class, io.nettyex.tinytransport.test.PBContent.ProtoContent.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>optional int32 cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int ERRCODE_FIELD_NUMBER = 2;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 2;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int ERRMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errMsg_;
    /**
     * <code>optional string errMsg = 3;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string errMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 20;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(1, cmd_);
      }
      if (errCode_ != 0) {
        output.writeInt32(2, errCode_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errMsg_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(20, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errCode_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errMsg_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.nettyex.tinytransport.test.PBContent.ProtoContent)) {
        return super.equals(obj);
      }
      io.nettyex.tinytransport.test.PBContent.ProtoContent other = (io.nettyex.tinytransport.test.PBContent.ProtoContent) obj;

      boolean result = true;
      result = result && (getCmd()
          == other.getCmd());
      result = result && (getErrCode()
          == other.getErrCode());
      result = result && getErrMsg()
          .equals(other.getErrMsg());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrCode();
      hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrMsg().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.ProtoContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.nettyex.tinytransport.test.PBContent.ProtoContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tinytransport.ProtoContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tinytransport.ProtoContent)
        io.nettyex.tinytransport.test.PBContent.ProtoContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_ProtoContent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_ProtoContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.nettyex.tinytransport.test.PBContent.ProtoContent.class, io.nettyex.tinytransport.test.PBContent.ProtoContent.Builder.class);
      }

      // Construct using io.nettyex.tinytransport.test.PBContent.ProtoContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        errCode_ = 0;

        errMsg_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_ProtoContent_descriptor;
      }

      public io.nettyex.tinytransport.test.PBContent.ProtoContent getDefaultInstanceForType() {
        return io.nettyex.tinytransport.test.PBContent.ProtoContent.getDefaultInstance();
      }

      public io.nettyex.tinytransport.test.PBContent.ProtoContent build() {
        io.nettyex.tinytransport.test.PBContent.ProtoContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.nettyex.tinytransport.test.PBContent.ProtoContent buildPartial() {
        io.nettyex.tinytransport.test.PBContent.ProtoContent result = new io.nettyex.tinytransport.test.PBContent.ProtoContent(this);
        result.cmd_ = cmd_;
        result.errCode_ = errCode_;
        result.errMsg_ = errMsg_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.nettyex.tinytransport.test.PBContent.ProtoContent) {
          return mergeFrom((io.nettyex.tinytransport.test.PBContent.ProtoContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.nettyex.tinytransport.test.PBContent.ProtoContent other) {
        if (other == io.nettyex.tinytransport.test.PBContent.ProtoContent.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getErrCode() != 0) {
          setErrCode(other.getErrCode());
        }
        if (!other.getErrMsg().isEmpty()) {
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.nettyex.tinytransport.test.PBContent.ProtoContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.nettyex.tinytransport.test.PBContent.ProtoContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ ;
      /**
       * <code>optional int32 cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 2;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 2;</code>
       */
      public Builder setErrCode(int value) {
        
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 2;</code>
       */
      public Builder clearErrCode() {
        
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string errMsg = 3;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errMsg = 3;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 3;</code>
       */
      public Builder clearErrMsg() {
        
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 3;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errMsg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 20;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 20;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 20;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tinytransport.ProtoContent)
    }

    // @@protoc_insertion_point(class_scope:tinytransport.ProtoContent)
    private static final io.nettyex.tinytransport.test.PBContent.ProtoContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.nettyex.tinytransport.test.PBContent.ProtoContent();
    }

    public static io.nettyex.tinytransport.test.PBContent.ProtoContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoContent>
        PARSER = new com.google.protobuf.AbstractParser<ProtoContent>() {
      public ProtoContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoContent> getParserForType() {
      return PARSER;
    }

    public io.nettyex.tinytransport.test.PBContent.ProtoContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetPersonInfoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tinytransport.GetPersonInfoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 area = 1;</code>
     */
    int getArea();

    /**
     * <code>optional string personId = 2;</code>
     */
    java.lang.String getPersonId();
    /**
     * <code>optional string personId = 2;</code>
     */
    com.google.protobuf.ByteString
        getPersonIdBytes();
  }
  /**
   * Protobuf type {@code tinytransport.GetPersonInfoReq}
   */
  public  static final class GetPersonInfoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tinytransport.GetPersonInfoReq)
      GetPersonInfoReqOrBuilder {
    // Use GetPersonInfoReq.newBuilder() to construct.
    private GetPersonInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetPersonInfoReq() {
      area_ = 0;
      personId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetPersonInfoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              area_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              personId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_GetPersonInfoReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_GetPersonInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq.class, io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq.Builder.class);
    }

    public static final int AREA_FIELD_NUMBER = 1;
    private int area_;
    /**
     * <code>optional int32 area = 1;</code>
     */
    public int getArea() {
      return area_;
    }

    public static final int PERSONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object personId_;
    /**
     * <code>optional string personId = 2;</code>
     */
    public java.lang.String getPersonId() {
      java.lang.Object ref = personId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string personId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPersonIdBytes() {
      java.lang.Object ref = personId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (area_ != 0) {
        output.writeInt32(1, area_);
      }
      if (!getPersonIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, personId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (area_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, area_);
      }
      if (!getPersonIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, personId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq)) {
        return super.equals(obj);
      }
      io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq other = (io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq) obj;

      boolean result = true;
      result = result && (getArea()
          == other.getArea());
      result = result && getPersonId()
          .equals(other.getPersonId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AREA_FIELD_NUMBER;
      hash = (53 * hash) + getArea();
      hash = (37 * hash) + PERSONID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tinytransport.GetPersonInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tinytransport.GetPersonInfoReq)
        io.nettyex.tinytransport.test.PBContent.GetPersonInfoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_GetPersonInfoReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_GetPersonInfoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq.class, io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq.Builder.class);
      }

      // Construct using io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        area_ = 0;

        personId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_GetPersonInfoReq_descriptor;
      }

      public io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq getDefaultInstanceForType() {
        return io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq.getDefaultInstance();
      }

      public io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq build() {
        io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq buildPartial() {
        io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq result = new io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq(this);
        result.area_ = area_;
        result.personId_ = personId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq) {
          return mergeFrom((io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq other) {
        if (other == io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq.getDefaultInstance()) return this;
        if (other.getArea() != 0) {
          setArea(other.getArea());
        }
        if (!other.getPersonId().isEmpty()) {
          personId_ = other.personId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int area_ ;
      /**
       * <code>optional int32 area = 1;</code>
       */
      public int getArea() {
        return area_;
      }
      /**
       * <code>optional int32 area = 1;</code>
       */
      public Builder setArea(int value) {
        
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 area = 1;</code>
       */
      public Builder clearArea() {
        
        area_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object personId_ = "";
      /**
       * <code>optional string personId = 2;</code>
       */
      public java.lang.String getPersonId() {
        java.lang.Object ref = personId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPersonIdBytes() {
        java.lang.Object ref = personId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public Builder setPersonId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public Builder clearPersonId() {
        
        personId_ = getDefaultInstance().getPersonId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public Builder setPersonIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tinytransport.GetPersonInfoReq)
    }

    // @@protoc_insertion_point(class_scope:tinytransport.GetPersonInfoReq)
    private static final io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq();
    }

    public static io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetPersonInfoReq>
        PARSER = new com.google.protobuf.AbstractParser<GetPersonInfoReq>() {
      public GetPersonInfoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetPersonInfoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetPersonInfoReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPersonInfoReq> getParserForType() {
      return PARSER;
    }

    public io.nettyex.tinytransport.test.PBContent.GetPersonInfoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonInfoResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tinytransport.PersonInfoRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 area = 1;</code>
     */
    int getArea();

    /**
     * <code>optional string personId = 2;</code>
     */
    java.lang.String getPersonId();
    /**
     * <code>optional string personId = 2;</code>
     */
    com.google.protobuf.ByteString
        getPersonIdBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string interest = 4;</code>
     */
    java.lang.String getInterest();
    /**
     * <code>optional string interest = 4;</code>
     */
    com.google.protobuf.ByteString
        getInterestBytes();
  }
  /**
   * Protobuf type {@code tinytransport.PersonInfoRes}
   */
  public  static final class PersonInfoRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tinytransport.PersonInfoRes)
      PersonInfoResOrBuilder {
    // Use PersonInfoRes.newBuilder() to construct.
    private PersonInfoRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonInfoRes() {
      area_ = 0;
      personId_ = "";
      name_ = "";
      interest_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PersonInfoRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              area_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              personId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              interest_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_PersonInfoRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_PersonInfoRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nettyex.tinytransport.test.PBContent.PersonInfoRes.class, io.nettyex.tinytransport.test.PBContent.PersonInfoRes.Builder.class);
    }

    public static final int AREA_FIELD_NUMBER = 1;
    private int area_;
    /**
     * <code>optional int32 area = 1;</code>
     */
    public int getArea() {
      return area_;
    }

    public static final int PERSONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object personId_;
    /**
     * <code>optional string personId = 2;</code>
     */
    public java.lang.String getPersonId() {
      java.lang.Object ref = personId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string personId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPersonIdBytes() {
      java.lang.Object ref = personId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTEREST_FIELD_NUMBER = 4;
    private volatile java.lang.Object interest_;
    /**
     * <code>optional string interest = 4;</code>
     */
    public java.lang.String getInterest() {
      java.lang.Object ref = interest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interest_ = s;
        return s;
      }
    }
    /**
     * <code>optional string interest = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInterestBytes() {
      java.lang.Object ref = interest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (area_ != 0) {
        output.writeInt32(1, area_);
      }
      if (!getPersonIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, personId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getInterestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, interest_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (area_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, area_);
      }
      if (!getPersonIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, personId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getInterestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, interest_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.nettyex.tinytransport.test.PBContent.PersonInfoRes)) {
        return super.equals(obj);
      }
      io.nettyex.tinytransport.test.PBContent.PersonInfoRes other = (io.nettyex.tinytransport.test.PBContent.PersonInfoRes) obj;

      boolean result = true;
      result = result && (getArea()
          == other.getArea());
      result = result && getPersonId()
          .equals(other.getPersonId());
      result = result && getName()
          .equals(other.getName());
      result = result && getInterest()
          .equals(other.getInterest());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AREA_FIELD_NUMBER;
      hash = (53 * hash) + getArea();
      hash = (37 * hash) + PERSONID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + INTEREST_FIELD_NUMBER;
      hash = (53 * hash) + getInterest().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.nettyex.tinytransport.test.PBContent.PersonInfoRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tinytransport.PersonInfoRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tinytransport.PersonInfoRes)
        io.nettyex.tinytransport.test.PBContent.PersonInfoResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_PersonInfoRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_PersonInfoRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.nettyex.tinytransport.test.PBContent.PersonInfoRes.class, io.nettyex.tinytransport.test.PBContent.PersonInfoRes.Builder.class);
      }

      // Construct using io.nettyex.tinytransport.test.PBContent.PersonInfoRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        area_ = 0;

        personId_ = "";

        name_ = "";

        interest_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.nettyex.tinytransport.test.PBContent.internal_static_tinytransport_PersonInfoRes_descriptor;
      }

      public io.nettyex.tinytransport.test.PBContent.PersonInfoRes getDefaultInstanceForType() {
        return io.nettyex.tinytransport.test.PBContent.PersonInfoRes.getDefaultInstance();
      }

      public io.nettyex.tinytransport.test.PBContent.PersonInfoRes build() {
        io.nettyex.tinytransport.test.PBContent.PersonInfoRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.nettyex.tinytransport.test.PBContent.PersonInfoRes buildPartial() {
        io.nettyex.tinytransport.test.PBContent.PersonInfoRes result = new io.nettyex.tinytransport.test.PBContent.PersonInfoRes(this);
        result.area_ = area_;
        result.personId_ = personId_;
        result.name_ = name_;
        result.interest_ = interest_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.nettyex.tinytransport.test.PBContent.PersonInfoRes) {
          return mergeFrom((io.nettyex.tinytransport.test.PBContent.PersonInfoRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.nettyex.tinytransport.test.PBContent.PersonInfoRes other) {
        if (other == io.nettyex.tinytransport.test.PBContent.PersonInfoRes.getDefaultInstance()) return this;
        if (other.getArea() != 0) {
          setArea(other.getArea());
        }
        if (!other.getPersonId().isEmpty()) {
          personId_ = other.personId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getInterest().isEmpty()) {
          interest_ = other.interest_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.nettyex.tinytransport.test.PBContent.PersonInfoRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.nettyex.tinytransport.test.PBContent.PersonInfoRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int area_ ;
      /**
       * <code>optional int32 area = 1;</code>
       */
      public int getArea() {
        return area_;
      }
      /**
       * <code>optional int32 area = 1;</code>
       */
      public Builder setArea(int value) {
        
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 area = 1;</code>
       */
      public Builder clearArea() {
        
        area_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object personId_ = "";
      /**
       * <code>optional string personId = 2;</code>
       */
      public java.lang.String getPersonId() {
        java.lang.Object ref = personId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPersonIdBytes() {
        java.lang.Object ref = personId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public Builder setPersonId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public Builder clearPersonId() {
        
        personId_ = getDefaultInstance().getPersonId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string personId = 2;</code>
       */
      public Builder setPersonIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object interest_ = "";
      /**
       * <code>optional string interest = 4;</code>
       */
      public java.lang.String getInterest() {
        java.lang.Object ref = interest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string interest = 4;</code>
       */
      public com.google.protobuf.ByteString
          getInterestBytes() {
        java.lang.Object ref = interest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string interest = 4;</code>
       */
      public Builder setInterest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string interest = 4;</code>
       */
      public Builder clearInterest() {
        
        interest_ = getDefaultInstance().getInterest();
        onChanged();
        return this;
      }
      /**
       * <code>optional string interest = 4;</code>
       */
      public Builder setInterestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interest_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tinytransport.PersonInfoRes)
    }

    // @@protoc_insertion_point(class_scope:tinytransport.PersonInfoRes)
    private static final io.nettyex.tinytransport.test.PBContent.PersonInfoRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.nettyex.tinytransport.test.PBContent.PersonInfoRes();
    }

    public static io.nettyex.tinytransport.test.PBContent.PersonInfoRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonInfoRes>
        PARSER = new com.google.protobuf.AbstractParser<PersonInfoRes>() {
      public PersonInfoRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PersonInfoRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonInfoRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonInfoRes> getParserForType() {
      return PARSER;
    }

    public io.nettyex.tinytransport.test.PBContent.PersonInfoRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinytransport_ProtoContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinytransport_ProtoContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinytransport_GetPersonInfoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinytransport_GetPersonInfoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinytransport_PersonInfoRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinytransport_PersonInfoRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PBContent.proto\022\rtinytransport\"J\n\014Prot" +
      "oContent\022\013\n\003cmd\030\001 \001(\005\022\017\n\007errCode\030\002 \001(\005\022\016" +
      "\n\006errMsg\030\003 \001(\t\022\014\n\004data\030\024 \001(\014\"2\n\020GetPerso" +
      "nInfoReq\022\014\n\004area\030\001 \001(\005\022\020\n\010personId\030\002 \001(\t" +
      "\"O\n\rPersonInfoRes\022\014\n\004area\030\001 \001(\005\022\020\n\010perso" +
      "nId\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\020\n\010interest\030\004 \001(" +
      "\t*>\n\003Cmd\022\013\n\007INVALID\020\000\022\022\n\016GET_PERSONINFO\020" +
      "\001\022\026\n\022GET_PERSONINFO_RES\020\002B\037\n\035io.nettyex." +
      "tinytransport.testb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tinytransport_ProtoContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tinytransport_ProtoContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinytransport_ProtoContent_descriptor,
        new java.lang.String[] { "Cmd", "ErrCode", "ErrMsg", "Data", });
    internal_static_tinytransport_GetPersonInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tinytransport_GetPersonInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinytransport_GetPersonInfoReq_descriptor,
        new java.lang.String[] { "Area", "PersonId", });
    internal_static_tinytransport_PersonInfoRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tinytransport_PersonInfoRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinytransport_PersonInfoRes_descriptor,
        new java.lang.String[] { "Area", "PersonId", "Name", "Interest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
